export const enum apiPath {
  dashboard = "/onboarding/members/me/dashboard",
  applyStudy = "/studies/apply",
  basicStudyInfo = "/common/studies",
  studyAnnouncementList = "announcements",
  studyDetails = "/studies/study-details",
  attend = "attend",
  myOngoingStudy = "/studies/me/ongoing",
  studyHistory = "/study-history",
  studyDetail = "/study-details/assignments",
  studyCurriculum = "/study-details/curriculums",
  dailyTask = "/study-details/todo",
  logout = "/auth/logout",
  members = "/common/members",
}
