import type { Assignment } from "types/dtos/studyDetail";
import type { AssignmentHistoryDto } from "types/dtos/studyHistory";

export const history: AssignmentHistoryDto[] = [
  {
    assignmentHistoryId: 1,
    status: "CANCELLED",
    title: "Assignment 1",
    deadline: "2024-08-17T06:02:17.417Z",
    descriptionLink: "",
    submissionLink: "http://example.com/submission1",
    assignmentSubmissionStatus: "SUCCESS",
    submissionFailureType: "NONE",
    week: 1,
  },
  {
    assignmentHistoryId: 2,
    status: "OPEN",
    title: "Assignment 2",
    deadline: "2024-08-24T06:02:17.417Z",
    descriptionLink: "http://example.com/assignment2",
    submissionLink: "",
    assignmentSubmissionStatus: "FAILURE",
    submissionFailureType: "WORD_COUNT_INSUFFICIENT",
    week: 2,
  },
  {
    assignmentHistoryId: 3,
    status: "OPEN",
    title: "Assignment 2",
    deadline: "2024-08-24T06:02:17.417Z",
    descriptionLink: "http://example.com/assignment2",
    submissionLink: "",
    assignmentSubmissionStatus: "FAILURE",
    submissionFailureType: "LOCATION_UNIDENTIFIABLE",
    week: 3,
  },
  {
    assignmentHistoryId: 3,
    status: "OPEN",
    title: "Assignment 2",
    deadline: "2024-08-24T06:02:17.417Z",
    descriptionLink: "http://example.com/assignment2",
    submissionLink: "",
    assignmentSubmissionStatus: "SUCCESS",
    submissionFailureType: "NONE",
    week: 3,
  },
];

export const assignmentData: Assignment[] = [
  {
    studyDetailId: 121,
    assignmentStatus: "OPEN",
    week: 4,
    title: "API Development",
    assignmentSubmissionStatus: "FAILURE",
    descriptionLink: "https://example.com/assignment/124",
    deadline: "2024-08-25T23:59:59",
    submissionLink: "https://github.com/GDSC-Hongik/wow-class",
    submissionFailureType: "LOCATION_UNIDENTIFIABLE",
    committedAt: "2024-08-20T14:30:00",
  },
  {
    studyDetailId: 122,
    assignmentStatus: "OPEN",
    week: 3,
    title: "Database Design Assignment",
    assignmentSubmissionStatus: "FAILURE",
    descriptionLink: "https://example.com/assignment/123",
    deadline: "2024-08-26T14:30:00",
    submissionLink: "https://github.com/GDSC-Hongik/wow-class",
    submissionFailureType: "NONE",
    committedAt: "2024-08-20T14:30:00",
  },
  {
    studyDetailId: 123,
    assignmentStatus: "OPEN",
    week: 3,
    title: "Database Design Assignment",
    assignmentSubmissionStatus: "SUCCESS",
    descriptionLink: "https://example.com/assignment/123",
    deadline: "2024-08-25T23:59:59",
    submissionLink: "https://github.com/GDSC-Hongik/wow-class",
    submissionFailureType: "NONE",
    committedAt: "2024-08-20T14:30:00",
  },
  {
    studyDetailId: 124,
    assignmentStatus: "OPEN",
    week: 3,
    title: "Database Design Assignment",
    assignmentSubmissionStatus: "FAILURE",
    descriptionLink: "https://example.com/assignment/123",
    deadline: "2024-08-25T23:59:59",
    submissionLink: "https://github.com/GDSC-Hongik/wow-class",
    submissionFailureType: "WORD_COUNT_INSUFFICIENT",
    committedAt: "sdf",
  },
  {
    studyDetailId: 125,
    assignmentStatus: "OPEN",
    week: 4,
    title: "API Development",
    assignmentSubmissionStatus: "FAILURE",
    descriptionLink: "https://example.com/assignment/124",
    deadline: "2024-08-25T23:59:59",
    submissionLink: "https://github.com/GDSC-Hongik/wow-class",
    submissionFailureType: "LOCATION_UNIDENTIFIABLE",
    committedAt: "2024-08-20T14:30:00",
  },
  //제출 안함/마감
  {
    studyDetailId: 126,
    assignmentStatus: "OPEN",
    week: 4,
    title: "API Development",
    assignmentSubmissionStatus: "FAILURE",
    descriptionLink: "https://example.com/assignment/124",
    deadline: "2024-08-20T14:30:00",
    submissionLink: "https://github.com/GDSC-Hongik/wow-class",
    submissionFailureType: "NOT_SUBMITTED",
    committedAt: "2024-08-20T14:30:00",
  },
  {
    studyDetailId: 127,
    assignmentStatus: "OPEN",
    week: 4,
    title: "API Development",
    assignmentSubmissionStatus: "FAILURE",
    descriptionLink: "https://example.com/assignment/124",
    deadline: "2024-08-25T23:59:59",
    submissionLink: "https://github.com/GDSC-Hongik/wow-class",
    submissionFailureType: "LOCATION_UNIDENTIFIABLE",
    committedAt: "2024-08-20T14:30:00",
  },
];
