export const routePath = {
  auth: "/auth",
  landing: "/landing",
  ["my-study"]: "/my-study",
  ["my-assignment"]: "/my-assignment",
  ["study-apply"]: "/study-apply",
  ["study-application-modal"]: "/study-apply/study-application",
  ["study-cancellation-modal"]: "/study-apply/study-cancellation",
  ["auth-error-during-recruitment"]: "/auth-error-during-recruitment",
  ["auth-error-after-recruitment"]: "/auth-error-after-recruitment",
  ["attendance-check"]: "/my-study/attendance-check",
  ["my-page"]: "/my-page",
  ["my-page-logout"]: "/my-page/logout",
  onboarding: "https://onboarding.gdschongik.com",
  github: "https://github.com",
} as const;
