export const enum tags {
  dashboard = "dashboard",
  studyApply = "studyApply",
  basicStudyInfo = "basicStudyInfo",
  studyDetailAnnouncementList = "studyAnnouncementList",
  allStudyAnnouncementList = "allStudyAnnouncementList",
  myOngoingStudy = "myOngoingStudy",
  studyHistory = "studyHistory",
  studyDetailDashboard = "studyDetailDashboard",
  upcomingStudy = "upcomingStudy",
  studyCurriculum = "studyCurriculum",
  dailyTask = "dailyTask",
  myAccountInfo = "myAccountInfo",
  myAppliedStudyList = "myAppliedStudyList",
  myStudyDetailDailyTask = "myStudyDetailDailyTask",
  allStudyTaskList = "allStudyTaskList",
}
