import "./global.css";
import "wowds-ui/styles.css";

import Navbar from "components/Navbar";
import type { Metadata } from "next";

import { JotaiProvider } from "../components/JotaiProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body>
        <JotaiProvider>
          <Navbar />
          {children}
        </JotaiProvider>
      </body>
    </html>
  );
};

export default RootLayout;
